name: Daily Commits

on:
  schedule:
    - cron: '20 10 * * *'  # Runs at 21:17 AET (11:17 UTC) every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  create-commits:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run commit script
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: python commit_script.py 